# -*- coding: utf-8 -*-
"""basic

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gArUZBxjtMdSi-BvIS_PTUwqlQJp-UIc

# Witamy w Colab
"""

i = 5
cena = 2.5
c = 2 + 5j
b = True
s = "Tekst"
n = None

print('wartosc zmiennej wynosi %.1f'%cena)

print(isinstance(i, int))

x=7
y=3
print(f'{x} + {y} = {x+y}')

s1 = 'to jest tekst jedno wierszowy'
s2="""to jest test,
ktory moge podzielic
na kilka linijek"""
s3="to tez jest dlugi tekst, ale zostal zapisany w jednym wierszu. i tak tez zostanie wyswietlony."
s4='ten tekst \ntez sklada sie z kilku wierszy, \nale zostal zapisany w jednej linii kodu'
s5='''kolejny tekst zapisany
w wielu liniac'''

print(s1,s2,s3,s4,s5, sep='\n')

s1='Ala ma kota'
print(s1)
print(s1.upper())
print(s1)
print(s1.lower())
print(s1)
s1=s1.lower()
print(s1)

s1="Ala ma kota"
print(s1)
s2=s1.replace("Ala","ola")
print(s1)
print(s2)
s3=s1.replace("Ala","Ola").replace("kota","psa")
print(s1)
print(s2)
print(s3)

s1="mam na imie {}. Mam {} lat i mieszkam w {}."
print(s1.format("Katarzyna", 18, "Krakowie"))
print(s1.format("Krzysztof", 25, "Warszawie"))

b1=bool(0)
b2=bool(1)
b3=bool(-1)
b4=bool(-10)
print(b1, b2, b3, b4, sep="\n")

b5=bool("Ala nie ma kota")
b6=bool("")
b7=bool(0.0)
b8=bool(1.5)
print(b5,b6,b7,b8,sep="\n")

i1=int(True)
i2=int(False)
f1=float(True)
f2=float(False)
s1=str(True)
s2=str(False)
print(i1,i2,f1,f2, sep="\n")

i=5
b=True
s="None"
n=None
#print(int(n))
#print(float(n))
print(str(n))
print(bool(n))

i=10
if i<0:
  print("liczba ujemna")
else:
  print("liczba dodatnia")

if i >=0:
  print("liczba dodatnia")
else:
  print("liczba ujemna")

i=0
if i==0: pass
else:
  print("i != 0")
i=10
if i==0: pass
else:
  print("i != 0")

#for
n= int(input("Podaj wartość n:"))

factorial=1
for i in range(1,n+1):
  factorial*=i

print(f"{n}! = {factorial}")

for i in range(2, n):
  if n% i ==0:
    print(f"{n} nie jest liczbą pierwszą")
    break
  else: print(f"{n} jest liczbą pierwszą")

n=int(input('podaj wartosc n:'))

for i in range (1, n+1):
  if i %2 == 0:
    print(f'{i} - liczba parzysta')
    continue
  print(f'{i} - liczba nieparzysta')

n=int(input('Podaj wartosc n:'))
if n >=0:

  print(f'{n}! =', end='')

  factorial=1

  while n>0:
    factorial *=n
    n -= 1

  print(factorial)
else:
  print('cos ty')

n=int(input('Podaj wartosc n:'))
i=2

while i<n:
  if n%i==0:
    print(f'{n} nie jest liczba pierwsza')
    break
  i +=1
else: print(f'{n} jest liczba pierwza')

prime=True
while prime:
  n=int(input('Podaj wartosc n: '))
  for i in range(2,n):
    if n%i==0:
      print(f'{n} nie jest liczba pierwsza')
      prime = False
      break
  else:
   print(f'{n} jest liczbą pierwszą')

l = list()
t=tuple()
s=set()
d=dict()

l = list()
t=tuple()
s=set()
d=dict()
print(f"""{l} => {type(l)}
{t} => {type(t)}
{s} => {type(s)}
{d} => {type(d)}
""")

list1=["ala","ola","krzys", "kubus"]
list2=[1,2,3,4,5]
list3=[True,False,True,True,False]
list4=["ala",5, 2.5, True, None]

print(list1)
print(list1[0])
print(list1[-1])
print(list1[1:-1])
for n in list1:
  print(n)
print(*list1)

print(list1)
list1[1]="ania"
print(list1)
if"ola" in list1:
  print("\"ola\" jest na liscie")
if"ania" in list1:
  print ("\"ania\"jest na liscie")
print("dlugosc listy: ",len(list1))

print(list1)
list1.append('piotrus')
print(list1)

list1.insert(2, "ola")
print(list1)
list1.remove("piotrus")
print(list1)

print(list1)
# If list1 is intended to be populated from previous operations,
# please ensure those cells are run before this one.
if list1:
  list1.pop()
  print(list1)
if list1:
  list1.pop()
  print(list1)
if list1:
  list1.pop(0)
  print(list1)
else:
  print("List is empty, no more elements to pop.")

list1 = ["ala", "ola", "krzys", "kubus"]

print(f"Oryginalna lista: {list1}")
list1.clear()
print(f"Lista po clear(): {list1}")

del list1
print("Zmienna list1 nadal istnieje, ale jest pusta.")

list1=["ala", "ola", "krzys", "kubus"]
list2=list1.copy()
list1.pop()
print(list1)
print(list2)

list1=['ala','ola','krzys','kubus']
list2=[1,2,3,4,5]
list3=list1+list2
print(list3)

list1=[5,3,2,7,6,4,9,1,8]
print(list1)
list1.sort()
print(list1)
list1.sort(reverse=True)
print(list1)

list1=[1,5,7,3,7,5,9,3,7,1]
print(list1.count(3))
print(list1.count(2))
print(list1.index(3))
print(list1.index(2))

tuple1=("ala","ola","krzys","kubus")

print(tuple1)
print(tuple1[0])
print(tuple1[-1])
print(tuple1[1:-1])



